### ISSUE TITLE
Exception in RuntimeSchema.createFrom(...)

### ISSUE THREAD

**Issue by kshchepanovskyi** [protostuff/protostuff#111]
We found very weird exception on one of our servers, after server restart it disappear. That server is using protostuff-1.0.8. Need to analyze why it could happen, if possible.  I do not exclude theory that something was deployed in wrong way.

```
Caused by: java.lang.NullPointerException [oapi-service-thread-3]
E 0317-1547:18,453  at com.dyuproject.protostuff.runtime.RuntimeSchema.createFrom(RuntimeSchema.java:236) [oapi-service-thread-3]
E 0317-1547:18,453  at com.dyuproject.protostuff.runtime.RuntimeSchema.createFrom(RuntimeSchema.java:147) [oapi-service-thread-3]
E 0317-1547:18,453  at com.playtech.openapi.core.frontend.messages.resolver.SchemaCache.createSchema(SchemaCache.java:45) [oapi-service-thread-3]
E 0317-1547:18,453  at com.playtech.openapi.core.frontend.messages.resolver.SchemaCache.getSchema(SchemaCache.java:37) [oapi-service-thread-3]
E 0317-1547:18,453  at com.playtech.openapi.core.frontend.messages.serialization.SerializationHolder.getSchema(SerializationHolder.java:29) [oapi-service-thread-3]
E 0317-1547:18,453  ... 6 more [oapi-service-thread-3]
```

**Comment by dyu** [comment]
Yeah weird indeed.  The error pointing to line 236 indicates that RuntimeFieldFactory.getFieldFactory returned null (if you look at the code, it never returns null).

My guess is it could be a classloading issue.  Though I'm not really sure why NPE is thrown.

Btw, if you guys are using protobuf format, switching to 1.0.9 won't break compat on your side and would make the protobuf serialization more efficient.

**Comment by kshchepanovskyi** [comment]
closed, not enough details
