### ISSUE TITLE
support syntax = "proto3" in protostuff parser

### ISSUE THREAD

**Issue by jnorthrup** [protostuff/protostuff#112]
feature request

**Comment by kshchepanovskyi** [comment]
+1

**Comment by kshchepanovskyi** [comment]
@jnorthrup do you have ideas what is expected date for final release? current release is only [alpha-2](https://github.com/google/protobuf/releases/tag/v3.0.0-alpha-2)

**Comment by jnorthrup** [comment]
it's live in grpc ( http://grpc.io )

**Comment by jnorthrup** [comment]
https://github.com/jnorthrup/prautobeans package uses the protostuff parser visitors  fwiw

**Comment by kshchepanovskyi** [comment]
@jnorthrup 
Parser for proto3 is 50% ready - https://github.com/kshchepanovskyi/proto-compiler
It is based on ANTLR4. You can check tests to see what is already supported.

**Comment by kshchepanovskyi** [comment]
You can check new parser that supports `proto3` here: https://github.com/protostuff/protostuff-compiler
Now it is in active development.
