### ISSUE TITLE
Custom options

### ISSUE THREAD

**Issue by kshchepanovskyi** [protostuff/protostuff#115]
I found that current parser implementation ~~ignore~~ *gives error for* custom options like these:

```proto
message MyMessage {
  option (foo.my_option) = { 
	x: 1 
	y: 2
	r: {
		r: 1
	}
  };
}

message MyMessage1 {
  option (foo.my_option).x = 1;
  option (foo.my_option).y = 2;
  option (foo.my_option).r.r = 1;
}
```

```proto
// foo.proto
syntax = "proto3";
import "google/protobuf/descriptor.proto";
package foo;

message Pair {
  int32 x = 1;
  int32 y = 2;
  R r = 3;
}

message R {
  int32 r = 1;
}

extend google.protobuf.MessageOptions {
  Pair my_option = 51234;
}
```

I am not sure that we should support such complicated scenarios in 1.x branch. Few days ago I started work on `proto3` parser based on ANTLR4, so most probably it will be supported in 2.x release.

**Comment by dyu** [comment]
Yep.  I had no need for complex static options like in protobuf.
Protostuff is very close to flatbuffer's dsl in terms of simplicity where the options/attributes are simple types and are dynamic (hash).
For my hybrid c++/java apps, I have a flatbuffers+protostuff dsl/generator which uses ST4 that works out of the box because of the similarity.

I know that those looking for proto3 compat would certainly welcome the new parser.

**Comment by kshchepanovskyi** [comment]
I really like ANTLR4, initially I was thinking it will be complex, but at the end I came to simple set of rules:

```antlr
option
    : optionName ASSIGN optionValue
    ;
optionName
    : NAME
    | customOptionName
    ;
customOptionName
    : '(' declarationRef ')' ('.' declarationRef)?
    ;
declarationRef
    : NAME ('.' NAME)*
    ;
optionValue
    : INTEGER_VALUE
    | BOOLEAN_VALUE
    | STRING_VALUE
    | textFormat
    ;
textFormat
    : '{' textFormatEntry* '}'
    ;
textFormatEntry
    : NAME ':' optionValue
    ;
```

**Comment by dyu** [comment]
By simple I meant options mapping to simple values (basically a hash with string key and any *dynamic* value, not a static user-defined option).

**Comment by kshchepanovskyi** [comment]
I understand :)

I'm using map with dynamic values too - it is the most efficient data structure in this case. 
The difference is that value for complex option is also `Map<String,Object>`, where values might be primitives or another maps (basically, it is a tree). For example, output of my `Enum.toString()` (one of unit tests) :

```
Enum{name=E, values=[], standardOptions={}, customOptions={core.foo={a=1, b=2, c={d=3}}}}
```

source:

```proto
enum E {
  option (core.foo).a = 1;
  option (core.foo).b = 2;
  option (core.foo).c.d = 3;
}
```

But that's not related to current protostuff implementation.

**Comment by kshchepanovskyi** [comment]
UPD: Maybe it makes sense to add parser rules for such options, but just to suppress errors. One of options from my project:

```proto
option (google.protobuf.objectivec_file_options).class_prefix = "LV2";
```

This line produces errors. We do not use it for code generation, but other team use (for objective c).

**Comment by dyu** [comment]
Forgive my late reply (Had a short vacation, whoa that was awesome!).  I'm not opposed to your proposal.  I definitely see the use-case where you want proto3 semantics.

**Comment by kshchepanovskyi** [comment]
UPD: I finished ANTLR4 parser, compatible with proto 2 specification: https://github.com/kshchepanovskyi/proto-compiler/blob/master/src/main/antlr4/io/protostuff/compiler/parser/ProtoParser.g4

I used protobuf's unit tests to ensure compatibility: https://github.com/kshchepanovskyi/proto-compiler/blob/master/src/test/resources/protobuf_unittest/unittest_custom_options.proto

All forms of custom options are supported. Currently I am working on validation part.

**Comment by dyu** [comment]
Nice work!

**Comment by kshchepanovskyi** [comment]
implemented in https://github.com/protostuff/protostuff-compiler
