### ISSUE TITLE
Latest release to maven repo?

### ISSUE THREAD

**Issue by phubner** [protostuff/protostuff#116]
Not really and issue but the latest version in the repo is 1.0.9 and there is a github release of 1.3.3. Are there plans to push the latest github releases to [Maven Repo](http://mvnrepository.com/artifact/com.dyuproject.protostuff) ?

**Comment by kshchepanovskyi** [comment]
Hi,

It is [already there](http://mvnrepository.com/artifact/io.protostuff), but with different groupId: `io.protostuff`

I updated [readme](https://github.com/protostuff/protostuff/blob/master/README.md) to avoid confusion.

**Comment by phubner** [comment]
Perfect! Thanks
