### ISSUE TITLE
Serialization and De-serialization of Throwable across JDK 1.6 and JDK 1.7 

### ISSUE THREAD

**Issue by mspavan052** [protostuff/protostuff#125]
Hi, 

   We have two system one Running with JDK 1.6 and another with JDK 1.7. To communicate between the two node we are using ProtoStuff Serialization to convert binary & transfer to other node where its again the binary is de-serialized. 

  JDK 1.7 added new field 'suppressedExceptions', so now if we serialize the Throwable in JDK 1.7 in one node and transfer to another node its not able de-serialize & vice versa. 

  As two nodes uses different technology its not possible to migrate from JDK 1.6 to JDK 1.7 & JDK 1.7 to JDK 1.6. 

 Is there any solution to solve this problem, Thanks in advance for the reply. 

With Regards,
Pavan

**Comment by kshchepanovskyi** [comment]
Hi,

In general, this issue has no solution. You cannot control field numbers (tags) in `RuntimeSchema`-s for classes that do not control. If you want control - you should write/generate `Schema<T>` for that class.

As a workaround, you can try to ignore `suppressedExceptions`. For example, you have some container class that with field of type `Throwable`:

```java
static class Container {

	public final Throwable e;

	public Container(Throwable e)
	{
		this.e = e;
	}
}

static class MyException extends RuntimeException {

	private String foo = "bar";

	public MyException(String message)
	{
		super(message);
	}
}
```

Code for testing:

```java
@Test
public void testSerialize() throws Exception
{
	MyException e = new MyException("root exception");
	MyException s = new MyException("suppressed exception");
	e.addSuppressed(s);
	Schema<Container> schema = RuntimeSchema.getSchema(Container.class);
	JsonIOUtil.writeTo(System.out, new Container(e), schema, true);
}

```

By default (JDK7), field `foo` will get number 5.

```json
{  
   "1":{  
      "52":"io.protostuff.runtime.ThrowableSerializationIT$MyException",
      "1":"root exception",
      "3":{  
         "1":0
      },
      "4":[  
         {  
            "52":"io.protostuff.runtime.ThrowableSerializationIT$MyException",
            "1":"suppressed exception",
            "3":{  
               "1":0
            },
            "5":"bar"
         }
      ],
      "5":"bar"
   }
}
```

We can use custom IdStrategy that "ignore" specific field for all classes that extend `Throwable`:

```java
static class CustomIdStrategy extends IdStrategy {

		@Override
		protected <T> Schema<T> newSchema(Class<T> typeClass)
		{
			if (Throwable.class.isAssignableFrom(typeClass)) {

				return RuntimeSchema.createFrom(typeClass, new String[] {"suppressedExceptions"}, this);
			}
			return super.newSchema(typeClass);
		}
```


Result: `foo` field number is 4. Field `suppressedExceptions` is ignored.

```json
{  
   "1":{  
      "52":"io.protostuff.runtime.ThrowableSerializationIT$MyException",
      "1":"root exception",
      "3":{  
         "1":0
      },
      "4":"bar"
   }
}
```

Full source: https://gist.github.com/kshchepanovskyi/fb289eaa5796ccc72d6e

**Comment by mspavan052** [comment]
Thanks for your quick reply, we also thought of using like this type of solution as below 
String[] excludeString = { "suppressedExceptions" };

RuntimeSchema.register(SubscribeServiceException.class, RuntimeSchema
.createFrom(SubscribeServiceException.class, excludeString, new DefaultIdStrategy()));

But in our code we have many different type of exceptions, so registering for each is difficult for the user ( Because we are sending user data which contain the exception ). Is there any way to make it generic i.e., to say all the classes inherited from the Throwable to should ignore suppressedExceptions. 


Once again thanks a lot for your reply.
