### ISSUE TITLE
Default constructor issue

### ISSUE THREAD

**Issue by awarrior** [protostuff/protostuff#132]
According to the demo, I deserialize my class object (for example `MyClass`) using `mergeDelimitedFrom` function. However, for the historical reason, `MyClass` has some initialization operation like `list.add("hello")` and I could not modify this. So before I deserialize my instance, it has been initialized and this action will do twice after I invoke `mergeDelimitedFrom`. Is there a way to figure out?
Here is my code:

```java
MyClass mc = new MyClass();
FileInputStream input = new FileInputStream(new File("text"));
Schema<MyClass> schema = RuntimeSchema.getSchema(MyClass.class);
LinkedBuffer buffer = LinkedBuffer.allocate(LinkedBuffer.DEFAULT_BUFFER_SIZE);
ProtostuffIOUtil.mergeDelimitedFrom(input, mc, schema, buffer);
```
PS: Also, I have tried another function `parseListFrom` but still not work.

**Comment by kshchepanovskyi** [comment]
Hi, can you please provide full code that reproduces a problem?

**Comment by awarrior** [comment]
Here is my testing code~
```java
public class test {
    public static void main(String[] args) {
        try {
            Schema<MyClass> schema = RuntimeSchema.getSchema(MyClass.class);
            LinkedBuffer buffer = LinkedBuffer.allocate(LinkedBuffer.DEFAULT_BUFFER_SIZE);

            FileOutputStream output = new FileOutputStream(new File("test.txt"));
            MyClass myClass = schema.newMessage();
            ProtostuffIOUtil.writeDelimitedTo(output, myClass, schema, buffer);
            output.close();

            System.out.println(myClass.getList().size()); // 1

            FileInputStream input = new FileInputStream(new File("test.txt"));
            MyClass myClassNew = schema.newMessage();
            buffer.clear();
            ProtostuffIOUtil.mergeDelimitedFrom(input, myClassNew, schema, buffer);
            input.close();

            System.out.println(myClassNew.getList().size()); // 2

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}

class MyClass {
    private List<String> list;
    public MyClass() {
        list = new ArrayList<>();
        list.add("hello");
    }
    public List<String> getList() {
        return list;
    }
}
```

**Comment by kshchepanovskyi** [comment]
Ok, I faced with similar issue in the past. In general, this is expected behavior: if class has a default constructor, then it is used for creating new object instances.

In your case two things happen: 

1. Default constructor adds an element to `list` when you create a message instance.
2. When you call `ProtostuffIOUtil.merge...`, it deserialize data and add other element to `list`.

As a possible solution that might work for such cases, we can force `RuntimeSchema` to use [sun.reflect.ReflectionFactory#newConstructorForSerialization](http://hg.openjdk.java.net/jdk8/jdk8/jdk/file/tip/src/share/classes/sun/reflect/ReflectionFactory.java#l325). But this solution is really unsafe and not portable (it will not work on Android).

I will check what we can do on next week.

**Comment by awarrior** [comment]
Thx for your reply :). I will have a try. And there is a doubt in my mind why not design some not-merge functions for deserializing and just accept an object. Hope to hear from you soon.

**Comment by kshchepanovskyi** [comment]
Hi,

I found a solution.

There is a system property that forces protostuff runtime to always use constructor for serialization: `protostuff.runtime.always_use_sun_reflection_factory`.

You should set this property to `true` on startup:

```java
System.setProperty("protostuff.runtime.always_use_sun_reflection_factory", "true");
```

Here is my unit test code:

```java
package io.protostuff.runtime;

import java.io.ByteArrayOutputStream;
import java.util.ArrayList;
import java.util.List;

import org.junit.Assert;
import org.junit.Test;

import io.protostuff.LinkedBuffer;
import io.protostuff.ProtostuffIOUtil;
import io.protostuff.Schema;

/**
 * @author Kostiantyn Shchepanovskyi
 */
public class AlwaysUseSunReflectionFactoryOptionTest {

	@Test
	public void forceUseSunReflectionFactory() throws Exception {
		System.setProperty("protostuff.runtime.always_use_sun_reflection_factory", "true");
		Schema<MyClass> schema = RuntimeSchema.getSchema(MyClass.class);
		ByteArrayOutputStream output = new ByteArrayOutputStream();
		MyClass myClass = new MyClass(); // constructor initializes list with one element
		ProtostuffIOUtil.writeTo(output, myClass, schema, LinkedBuffer.allocate());
		byte[] bytes = output.toByteArray();
		Assert.assertEquals(1, myClass.getList().size());
		MyClass myClassNew = schema.newMessage(); // default constructor should not be used
		ProtostuffIOUtil.mergeFrom(bytes, myClassNew, schema);
		Assert.assertEquals(1, myClassNew.getList().size());
	}

	final static class MyClass {
		private List<String> list;

		public MyClass() {
			list = new ArrayList<>();
			list.add("hello");
		}

		public List<String> getList() {
			return list;
		}
	}

}
```

**Comment by awarrior** [comment]
Hi, @kshchepanovskyi it's a really nice solution and help me a lot. Thx~
