### ISSUE TITLE
compiled release

### ISSUE THREAD

**Issue by clankill3r** [protostuff/protostuff#134]
Hi,
i'm new to serialization since today. I saw a great link in StackOverFlow comparing a lot of serialization libraries. Protostuff did really well on those benchmarks. And often i'm not a huge van of the default java libraries.

I only wonder some things about protostuff:

1). Why isn't a compiled release included in the download? (and what is the easiest way to compile?)
2). Do I only need the core? And if not, what folders are important, there are 18 of them... 
3). Do I need to have maven?

I hope someone can help. A link to some good tutorial is also welcome but I couldn't find any descent tutorial.

**Comment by kshchepanovskyi** [comment]
Hi @clankill3r 

It is a best practice to use build system, for java we have many of them - the most popular are - [maven](https://maven.apache.org/index.html) and [gradle](https://gradle.org/).

Here is an example how to use protostuff with maven: https://github.com/protostuff/protostuff-examples/tree/master/hello-world

If you want store jar files locally, then you can find all released artifacts in maven-central: http://mvnrepository.com/artifact/io.protostuff.
For example, protostuff-core is here: http://central.maven.org/maven2/io/protostuff/protostuff-core/1.3.6/protostuff-core-1.3.6.jar

Compilation is trivial - you should install maven and run following on project root:

```
$ mvn clean install
```

**Comment by clankill3r** [comment]
Thanks for the reply.

What makes that example a maven example? I can't find anything in `HelloService.java` related to maven.

**Comment by kshchepanovskyi** [comment]
> What makes that example a maven example?

[pom.xml](https://github.com/protostuff/protostuff-examples/blob/master/hello-world/pom.xml)

**Comment by kshchepanovskyi** [comment]
@clankill3r What would you like to see in the tutorial? 

I'm going to write tutorial on the next week - basically I will put all existing documentation to one place. I can add some things that looks obvious to me, but are not obvious to people new to java.
