### ISSUE TITLE
Different filenames for generated sources

### ISSUE THREAD

**Issue by SemionPar** [protostuff/protostuff#136]
Is there a way to change the generated protostuff classes names by the maven plugin (change required is adding a *Proto suffix to each generated class)? 
All I found was [this thread](https://groups.google.com/forum/#!topic/protostuff/tb3-SzLzj9g), but changes to plugin seem not to be implemented. Oh, please tell me that I am wrong :)

**Comment by kshchepanovskyi** [comment]
It is possible with `PluginProtoCompiler`. You should create new `stg` template with name `$Proto.java.stg`. In this template, [find place where class name is generated](https://github.com/kshchepanovskyi/protostuff/blob/master/protostuff-compiler/src/main/resources/io/protostuff/compiler/java_bean.stg#L109-109) and add suffix `Proto`.

**Comment by kshchepanovskyi** [comment]
You can check this example: https://github.com/protostuff/protostuff-examples/tree/master/code-generation/plugin-proto-compiler
