### ISSUE TITLE
Check issues from googlecode

### ISSUE THREAD

**Issue by kshchepanovskyi** [protostuff/protostuff#137]
~~Import~~ Check issues from https://github.com/protostuff/protostuff-googlecode-exported

**Comment by kshchepanovskyi** [comment]
After importing issues & wiki pages, we can drop that project.

**Comment by dyu** [comment]
The notice on the front page should be enough for people to refer to this project on github.
It has been already archived and read-only.

**Comment by kshchepanovskyi** [comment]
Right, but google code [will not keep it forever](http://google-opensource.blogspot.com.ee/2015/03/farewell-to-google-code.html].
