### ISSUE TITLE
Reduce number of modules

### ISSUE THREAD

**Issue by kshchepanovskyi** [protostuff/protostuff#141]
Seems that some modules can be joined together:
* `protostuff-runtime-view`
* `protostuff-runtime-registry`
* `protostuff-collectionschema`

They all can be just merged into `protostuff-runtime`.

@dyu what do you think? Are there any good reasons to keep them as is and release as separate jars?

**Comment by dyu** [comment]
They can be merged sure, but registry and view are optional dependencies.  Which is why they're separate.  The collectionschema can be used standalone, when you just want to extend a schema based on your custom datastructure/container impl.

**Comment by kshchepanovskyi** [comment]
> registry and view are optional dependencies

Right, but they are so small so I think it is better to make them part of `protostuff-runtime`. 

In general, I would like to do some simplification of the project structure. And if there are some things that can be merged together (like a module with two classes), or even remove - better to do it, because support costs are high. Especially when some things are not covered by automated tests (like some code generators).

**Comment by dyu** [comment]
Ok, they can be merged.  The users just need to use a tool to strip unused dependencies, that is, if that kind of thing is important to them.

**Comment by kshchepanovskyi** [comment]
Yes - if size matters. On android it is a [common practice](http://developer.android.com/tools/help/proguard.html).
For server-side projects - I hardly believe somebody really does this :)
