### ISSUE TITLE
Maven plugin: better include support

### ISSUE THREAD

**Issue by technocoreai** [protostuff/protostuff#143]
It's currently very hard to manage multiple Maven projects that use protostuff modules when some of them use schemas provided by the other projects. Right now we have to resort to complicated hacks: publish `src/main/proto/*` in the base module as a separate zip artifact, then in the module that uses those includes call `unpack-dependencies` and use `properties-maven-plugin:set-system-properties` to munge the `proto_path` property.

This could be much easier if the Maven plugin could do the following (either by default or with an explicit option):
 * packaged the contents of `src/main/proto` inside the main jar, using the proto package name as the resource path
 * automatically included the schemas from all jars on the compile classpath when compiling the project

This would make such complicated setups work pretty much transparently: the base module would have `foo/bar/common.proto` in the built jar, and the modules that use it would be able to just do `import "foo/bar/common.proto"`, which would do the right thing.

**Comment by kshchepanovskyi** [comment]
Hi @technocoreai 
 
It is [already implemented](https://github.com/protostuff/protostuff/pull/38) (and released with version 1.2.0). [Check this example](https://github.com/protostuff/protostuff-examples/tree/master/multimodule-imports).

**Comment by technocoreai** [comment]
Oops! Sorry for bothering you then. :)
