### ISSUE TITLE
Parameter Access

### ISSUE THREAD

**Issue by jelgh** [protostuff/protostuff#144]
Hi,

Have you got any plans on making it possible to annotate a get-method with @Tag in order to get parameter access ?

Just close this issue if you have answered this else-where or if I'm in the wrong place asking this question.

Best,
Johannes

**Comment by kshchepanovskyi** [comment]
Hi,

No, there is no such plans. `RuntimeSchema` uses fields [directly](https://github.com/protostuff/protostuff/blob/protostuff-1.3.6/protostuff-runtime/src/main/java/io/protostuff/runtime/RuntimeSchema.java#L200), there is no way to use getters/setters.

Why do you need this?

**Comment by jelgh** [comment]
I generally feel it's a good feature but my particular case is as follows:

I have an Amount object that I want to embed in different objects. These object (that carry the Amount) are shared between serialization to database (cassandra) and out on API (with protobuf). The Amount object has two fields `value` and `currency`. 
So when serializing to cassandra I would want this to two columns (unfortunately an automatic solution is not yet supported). Therefore I need to have fields `amount_value` and `amount_currency` for cassandra. 
However, on my API I don't want these two fields, I want an Amount object. Using Jackson for json serialization, I can `@JsonIgnore` the two amount-fields and annotate a method: 
```
@JsonProperty("amount")
public Amount getAmount() {
    return new Amount(amount_value, amount_currency);
}
```

**Comment by kshchepanovskyi** [comment]
Ok, I undestand. Maybe you can use other solution - write custom schema for your class.
Your class should implement interface [Message](https://github.com/protostuff/protostuff/blob/master/protostuff-api/src/main/java/io/protostuff/Message.java) - then `RuntimeSchema` must use custom schema instead of generating new one.

**Comment by kshchepanovskyi** [comment]
> I generally feel it's a good feature

Yes, it is :) If you want, you can try to implement it.

**Comment by jelgh** [comment]
Solved it by having a Cassandra-prefixed class and a copy constructor
basically. Might try to implement it anyways sometime!
