### ISSUE TITLE
FlushHandler usage

### ISSUE THREAD

**Issue by kshchepanovskyi** [protostuff/protostuff#146]
@dyu,

I cannot find any usages, tests or documentation for [io.protostuff.WriteSession.FlushHandler](https://github.com/protostuff/protostuff/blob/67b83cb40a27f40e425273ef2348becbdab8310c/protostuff-api/src/main/java/io/protostuff/WriteSession.java#L30) - can I drop it?

**Comment by dyu** [comment]
I used it to override the default flush behavior without having to extend
the class.

On Thursday, October 15, 2015, Kostiantyn Shchepanovskyi <
notifications@github.com> wrote:

> @dyu <https://github.com/dyu>,
>
> I cannot find any usages/documentation for
> io.protostuff.WriteSession.FlushHandler
> <https://github.com/protostuff/protostuff/blob/67b83cb40a27f40e425273ef2348becbdab8310c/protostuff-api/src/main/java/io/protostuff/WriteSession.java#L30>
> - can I drop it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/protostuff/protostuff/issues/146>.
>


-- 
When the cat is away, the mouse is alone.
- David Yu
