### ISSUE TITLE
cannot serialize Locale

### ISSUE THREAD

**Issue by dicolar** [protostuff/protostuff#147]
seems that java.util.Locale cannot be serialized correctly,any idea with it?
here's my code:

```java
Schema<Locale> schema = RuntimeSchema.getSchema(Locale.class);

Locale locale = Locale.getDefault();
LinkedBuffer buffer = LinkedBuffer.allocate(4096);
byte[] bytes = ProtostuffIOUtil.toByteArray(locale, schema, buffer);
System.out.println(bytes.length);//it's 0
System.out.println(new String(bytes));// blank string

Locale l = new Locale("", "aa");
ProtostuffIOUtil.mergeFrom(bytes, l, schema);

System.out.println(l);//nothing changed
```

**Comment by kshchepanovskyi** [comment]
All fields in the `Locale` class are transient, it cannot be serialized in this way.

I think you can solve this issue with custom [Delegate](http://www.protostuff.io/documentation/runtime-schema-delegate/).

**Comment by dicolar** [comment]
yeah,it works!i modified my code like this,is it right or do u have any advise on it?

```
public static final Delegate<Locale> LOCALE_DELEGATE = new Delegate<Locale>() {
		public Class<?> typeClass() {
			return Locale.class;
		}

		public WireFormat.FieldType getFieldType() {
			return WireFormat.FieldType.STRING;
		}

		public void writeTo(Output output, int number, Locale value,
							boolean repeated) throws IOException {
			output.writeString(number, value.getLanguage() + "|" + value.getCountry(), repeated);
		}

		public Locale readFrom(Input input) throws IOException {
			String[] arr = input.readString().split("\\|");
			return new Locale(arr[0], arr[1]);
		}

		public void transfer(Pipe pipe, Input input, Output output, int number, boolean repeated)
				throws IOException {
			output.writeString(number, input.readString(), repeated);
		}
	};

	static {
		IncrementalIdStrategy.Registry r = new IncrementalIdStrategy.Registry(20, 11, 20, 11, 20, 11, 80, 11);
		r.registerDelegate(LOCALE_DELEGATE, 1);
		SCHEMA = RuntimeSchema.getSchema(NetMessage.class, r.strategy);
	}
```

**Comment by dicolar** [comment]
hi again,i read the code&found a weird but useful way 2 build up my code,like this:

```
static {
	DefaultIdStrategy strategy = (DefaultIdStrategy) RuntimeEnv.ID_STRATEGY;
	strategy.registerDelegate(LOCALE_DELEGATE);
	SCHEMA = RuntimeSchema.getSchema(NetMessage.class);
}
```

because when i use `IncrementalIdStrategy` 2 build schema each time,i found that i cannot de-serialize the bytes which i stored last time.i think `IncrementalIdStrategy` has some internal random factors that is different when i use it each time.

**Comment by kshchepanovskyi** [comment]
Please use `DefaultIdStrategy`.

I never used `IncrementalIdStrategy` by the same reason - it is unstable (auto-generated identifiers are not stable). @dyu we should think about removing it in the following major release.

**Comment by dicolar** [comment]
ok!thank u 4 answerin my question !

**Comment by dyu** [comment]
@kshchepanovskyi Its only useful if the IncrementalIdStrategy is serialized before shutdown and written to some file and loaded on init (for services that cache 3rd party pojos).

Having said that, DefaultIdStrategy (although a bit bigger size-wise) could also cache 3rd party pojos and is not error-prone, so its fine with me if it is removed.

**Comment by eonezhang** [comment]
it's useful for me, great, thanks.
