### ISSUE TITLE
JSON deserialization fails for unknown message fields

### ISSUE THREAD

**Issue by kshchepanovskyi** [protostuff/protostuff#149]
Related to https://github.com/protostuff/protostuff-googlecode-exported/issues/13

https://github.com/protostuff/protostuff/blob/protostuff-1.3.6/protostuff-json/src/main/java/io/protostuff/JsonInput.java#L119

```java
    @Override
    public <T> void handleUnknownField(int fieldNumber, Schema<T> schema) throws IOException
    {
        if (parser.getCurrentToken().isScalarValue())
        {
            // numeric json
            // we can skip this unknown field
            if (lastRepeated)
            {
                lastRepeated = false;
                // skip the scalar elements
                while (parser.nextToken() != END_ARRAY)
                    ;
            }
            return;
        }

        throw new JsonInputException("Unknown field: " +
                (numeric ? fieldNumber : lastName) +
                " on message " +
                schema.messageFullName());
    }
```
@dyu why did you decide to fail if field is non-scalar?

I think default behavior should be "ignore all unknown fields".

**Comment by kshchepanovskyi** [comment]
I see there is similar code in `XmlInput` and there is a comment:

```java
// we do not know how deep this message is
```

Is this the reason?

**Comment by dyu** [comment]
It was simpler to ignore scalar fields only.
Recursively ignoring fields from a nested message can be done though I didn't put a TODO there to implement it in the future.

**Comment by kshchepanovskyi** [comment]
ok
