### ISSUE TITLE
RuntimeSchema.getSchema clear cache?

### ISSUE THREAD

**Issue by tinustate** [protostuff/protostuff#153]
I'm using protostuff for the communication between server and clients, works great! I use RuntimeSchema to create a schema from unknown pojo's.

I used to use RuntimeSchema.getSchema but I'm now force to use RuntimeSchema.createFrom. Because getSchema uses an internal cache to speed things up. This cache causes problems when classes are "reloaded" with osgi, the new classes are not seen by getSchema (like because the old ones are still in the cache)

I was wondering is there a way to clear or reset the cache used by getSchema ? This way i could still use the faster getSchema and when osgi deploys an bundle i can clear the cache.

**Comment by kshchepanovskyi** [comment]
Technically it is possible, but there might be better solution.

We can introduce `RuntimeSchemaFactory` - it will not be `static`, so you will need an instance of this factory to create a schema instance. But it will be a lot more flexible than global static factory.

I have this in plans for next major release, but if you think that it can solve your problem - we can add it to release 1.4.

**Comment by tinustate** [comment]
I suspect this will solve my problem ;-) When i understand it correctly i will create an singleton containing the RuntimeSchemaFactory instance, any calls to getSchema will be handled by that instance (and cache). When an osgi bundle is installed/updated i simply create a new RuntimeSchemaFactory instance in my singleton (which would have an empty cache).

Thanks for the support! I'm looking forward to the 1.4 release.

**Comment by dyu** [comment]
https://code.google.com/p/protostuff/issues/detail?id=137 - this has come up before.
So instead of calling RuntimeSchema.getSchema(class), you create a wrapper class with the same signature:
```java
public final class SchemaSource
{
    // reconstruct this when classes are reloaded
    private static IdStrategy idStrategy = new DefaultIdStrategy();

    public static <T> Schema<T> getSchema(Class<T> typeClass)
    {
        return RuntimeSchema.getSchema(class, idStrategy);
    }
}
// so now you find and replace all RuntimeSchema.getSchema calls to SchemaSource.getSchema
```
@kshchepanovskyi The IdStrategy holds all the cache and is basically the  RuntimeSchemaFactory that you proposed.  The solution above could be achieved by supplying your own custom IdStrategy instance with reload logic (though I recommend doing the example above as it is simpler)

**Comment by tinustate** [comment]
@dyu thanks for the suggestion! I implemented your solution this morning and did a few tests and it works without problems. Replacing the idStrategy with a new instance, like you suggested, does reset the class cache.

**Comment by kshchepanovskyi** [comment]
@dyu You are right. There is a way to solve issue, so lets keep things as is for now.

Anyway, it is not very clear why "id strategy" is responsible for schema caching. This class should have only one responsibility. As a result of current design, some parts of code are duplicated:

* `io.protostuff.runtime.DefaultIdStrategy.Lazy#getSchema`
* `io.protostuff.runtime.ExplicitIdStrategy.Lazy#getSchema`

So this part of code can be improved.

**Comment by dyu** [comment]
@kshchepanovskyi I guess it would have been clearer if the name was CachingStrategy (where the cache key would be by fqcn or int)
