### ISSUE TITLE
LinkBuffer's getBuffers should include the current buffer

### ISSUE THREAD

**Issue by joshua-g** [protostuff/protostuff#16]
One use case for LinkBuffer#getBuffers is to look at all the data written so far, in order to compute a checksum or CRC. Since getBuffers doesn't return the current buffer, it's not possible to do that without first calling finish().

See: https://github.com/protostuff/protostuff/blob/master/protostuff-core/src/main/java/com/dyuproject/protostuff/LinkBuffer.java#L52

**Comment by kshchepanovskyi** [comment]
fixed
