### ISSUE TITLE
Field with name "class" generates invalid Java code

### ISSUE THREAD

**Issue by j-pedro-fonseca** [protostuff/protostuff#163]
A field named "class" will generate invalid Java code - the corresponding "getClass" method is already defined in the Object superclass.

The following error is reported when compiling:

error: getClass() in XXX cannot override getClass() in Object

**Comment by kshchepanovskyi** [comment]
Good catch. Interesting, how it is solved in protobuf compiler.

**Comment by kshchepanovskyi** [comment]
`protoc` generates following java code:

```java
/**
 * <code>optional int32 class = 1;</code>
 */
int getClass_();
```
