### ISSUE TITLE
how to get comments in Message of Field ?

### ISSUE THREAD

**Issue by PaniniGelato** [protostuff/protostuff#172]
hi,

I am running a program to parse .proto file with comments.

The codes are as blow:
```
    File f = getFile("TestModel.proto");
    Proto proto = new Proto(f);
    ProtoUtil.loadFrom(f, proto);
    System.out.println("proto docs : " + proto.getDocs().size());
		
    Message foo = proto.getMessage("Foo");
    System.out.println("proto docs : " + foo.getDocs().size());
		
    Field field = foo.getField("some_int");
    System.out.println("proto docs : " + field.getDocs().size());
```

The .proto is  as blow:
```
// this is Foo
message Foo {
  enum EnumSample {
    TYPE0 = 0;
    TYPE1 = 1;
    TYPE2 = 2;
    TYPE3 = 3;
    TYPE4 = 4;
  }
  repeated int32 some_int = 1; // this is some_int
}
```

I tried v1.4.0, v1.3.5 and v1.3.4 but all the docs returned empty.

Do I miss something?
Looking forward to your reply. Thank u.

**Comment by kshchepanovskyi** [comment]
Hi. 

In 1.x branch comments are not fully supported - you should use `///` to make comment appear in `docs`.

We have new parser - `io.protostufff:protostuff-parser-2.0.0-alpha10` (latest version). It has better support for parsing comments.
You can use this test as a starting point: https://github.com/protostuff/protostuff-compiler/blob/master/protostuff-parser/src/test/java/io/protostuff/compiler/parser/CommentsTest.java

**Comment by PaniniGelato** [comment]
understood. I will use '///' in my case.

Thank u very much
