### ISSUE TITLE
Problem with serializing custom Collections

### ISSUE THREAD

**Issue by thinline72** [protostuff/protostuff#176]
Hello,

I'm a developer of [Apache Cayenne ORM framework](https://github.com/apache/cayenne). We are going to use Protostuff runtime object graph serialization for our ROP functionality instead of Hessian. So, I'm working on [cayenne-protostuff module](https://github.com/thinline72/cayenne/tree/cayenne-protostuff/cayenne-protostuff).

Unfortunately, I faced the problem with serializing custom collections. I use `protostuff.runtime.collection_schema_on_repeated_fields=true` and `protostuff.runtime.morph_collection_interfaces=true`. Even if I provide custom schema or preregister runtime generated schema, Protostuff treats my custom collection as Collection during serialization process and doesn't serialize any additional fields. Below are example of usage and some details about what happens on Protostuff side.

There is a custom List implementation [PersistentObjectList](https://github.com/apache/cayenne/blob/master/cayenne-server/src/main/java/org/apache/cayenne/util/PersistentObjectList.java) in Cayenne, which is extended from [RelationshipFault](https://github.com/apache/cayenne/blob/master/cayenne-server/src/main/java/org/apache/cayenne/util/RelationshipFault.java). RelationshipFault has two important fields "relationshipOwner" and "relationshipName".

So if I serialize PersistentObjectList directly (as parent), it works fine:
```java
@Test
public void testPersistentObjectListAsParent() {
    Schema<PersistentObjectList> schema = RuntimeSchema.getSchema(PersistentObjectList.class);
    PersistentObjectList list = new PersistentObjectList(new MtTable1(), "test");

    byte[] bytes = GraphIOUtil.toByteArray(list, schema, LinkedBuffer.allocate());
    PersistentObjectList list0 = schema.newMessage();
    GraphIOUtil.mergeFrom(bytes, list0, schema);

    assertNotNull(list0.getRelationshipOwner()); // true, {<no id>; transient; []}
    assertNotNull(list0.getRelationshipName()); // true, test
}
```

But usually PersistentObjectList is a nested object. For simplicity, I just wrap it by simple Wrapper.
```java
public class Wrapper implements Serializable {
    public Object data;
    
    public Wrapper(Object data) {
        this.data = data;
    }
}

@Test
public void testPersistentObjectListWithWrapper() {
    Schema<Wrapper> schema = RuntimeSchema.getSchema(Wrapper.class);
    PersistentObjectList list = new PersistentObjectList(new MtTable1(), "test");

    byte[] bytes = GraphIOUtil.toByteArray(new Wrapper(list), schema, LinkedBuffer.allocate());
    Wrapper result = schema.newMessage();
    GraphIOUtil.mergeFrom(bytes, result, schema);
    PersistentObjectList list0 = (PersistentObjectList) result.data;

    assertNotNull(list0.getRelationshipOwner()); // false, null
    assertNotNull(list0.getRelationshipName()); // false, null
}
```

So, what happens on Protostuff side. Here is some kind of stack-trace:
[GraphIOUtil.java:261](https://github.com/protostuff/protostuff/blob/master/protostuff-core/src/main/java/io/protostuff/GraphIOUtil.java#L261)
[RuntimeSchema.java:457](https://github.com/protostuff/protostuff/blob/master/protostuff-runtime/src/main/java/io/protostuff/runtime/RuntimeSchema.java#L457) // Here Protostuff gets a field with PersistentObjectList
[RuntimeUnsafeFieldFactory.java:1231](https://github.com/protostuff/protostuff/blob/master/protostuff-runtime/src/main/java/io/protostuff/runtime/RuntimeUnsafeFieldFactory.java#L1231) // Here it starts to writeObject with PersistentObjectList
[GraphProtostuffOutput.java:64](https://github.com/protostuff/protostuff/blob/master/protostuff-core/src/main/java/io/protostuff/GraphProtostuffOutput.java#L64)
[ObjectSchema.java:356](https://github.com/protostuff/protostuff/blob/master/protostuff-runtime/src/main/java/io/protostuff/runtime/ObjectSchema.java#L356)
[ObjectSchema.java:945](https://github.com/protostuff/protostuff/blob/master/protostuff-runtime/src/main/java/io/protostuff/runtime/ObjectSchema.java#L945) // Here it treats PersistentObjectList as Collection
[IdStrategy.java:554](https://github.com/protostuff/protostuff/blob/master/protostuff-runtime/src/main/java/io/protostuff/runtime/IdStrategy.java#L554) // And here it applies Protostuff's COLLECTION_SCHEMA and DYNAMIC_VALUE_SCHEMA, which doesn't serialize any additional fields

Am I doing something wrong? Is it another way how to deal with custom collections?
I think the main issue is that Protostuff doesn't check for any registered schemas here [ObjectSchema.java:716](https://github.com/protostuff/protostuff/blob/master/protostuff-runtime/src/main/java/io/protostuff/runtime/ObjectSchema.java#L716) before checking for Collection (or whatever else). So, how about to check for existing schemas, as it's already done for [delegates](https://github.com/protostuff/protostuff/blob/master/protostuff-runtime/src/main/java/io/protostuff/runtime/ObjectSchema.java#L718)?

Thanks!

**Comment by kshchepanovskyi** [comment]
Released version 1.4.3

**Comment by thinline72** [comment]
Thanks a lot for all your work!

**Comment by dyu** [comment]
@thinline72 If your dataset has lots of collections, updating to 1.5.2 would be a good idea (better perf especially on deser)

**Comment by thinline72** [comment]
Thanks, @dyu!
