### ISSUE TITLE
java bean 2 proto file?

### ISSUE THREAD

**Issue by kaybinwong** [protostuff/protostuff#198]
how to generate a Java Bean to a proto file?

**Comment by dyu** [comment]
Try this one - https://github.com/webbynet/protostuff-runtime-proto

**Comment by kaybinwong** [comment]
thx a lot, i had found this project.
somebody may generate java bean to proto file, have any idea to integrate it to the protostuff project ?

**Comment by kshchepanovskyi** [comment]
No, unfortunately there is no plan for that.
