### ISSUE TITLE
proto3 support?

### ISSUE THREAD

**Issue by gan123** [protostuff/protostuff#202]
Hi,
Is 1.5.2 meant for proto3 or proto2? We are trying to use this on our java server to deserialize incoming message (sent in proto3 format from client using google.protobuf). But the server side seems to fail everytime it tries to deserialize. However if the server sends the serialized object to the client, the client is able to deserialize it successfully (probably because google.protobuf for proto3 is backward compatible with proto2), but with incorrect values in the object.

We need to sort this out ASAP. Any help, leads here is much appreciated.

Cheers!
Ganesh

**Comment by kshchepanovskyi** [comment]
Can you please show some code that reproduces the problem? Ideally, in a
form of a test where you serialize data using protobuf 3 classes and then
deserialize it using protostuff.

1 лист. 2016 р. 10:42 дп "gan123" <notifications@github.com> пише:

**Comment by gan123** [comment]
Never mind. The problem was between List<> vs array[]. Changing everything to List<> on java seemed to have solved the problem. But is 1.5.2 meant for proto3?

**Comment by kshchepanovskyi** [comment]
Binary format is same and protostuff library can work with proto3 on remote
side, but there might be problems, especially with RuntimeSchema.

2 лист. 2016 р. 3:59 дп "gan123" <notifications@github.com> пише:
