### ISSUE TITLE
Where can find some materials about code generation in Protostuff?

### ISSUE THREAD

**Issue by harryyu1018** [protostuff/protostuff#203]
Hi guys, I want to know more about the implement of code generation in Protostuff. Where I can find these materials? thx

**Comment by kshchepanovskyi** [comment]
Hi, we have new code generator in https://github.com/protostuff/protostuff-compiler project.

Java code generator is based on http://www.stringtemplate.org/
You can find all templates here: https://github.com/protostuff/protostuff-compiler/tree/master/protostuff-generator/src/main/resources/io/protostuff/generator/java
