### ISSUE TITLE
wiki: Eclipse IDE - Plugin execution not covered by lifecycle configuration: io.protostuff:protostuff-maven-plugin:1.3.5:compile (execution: generate-sources, phase: generate-sources)

### ISSUE THREAD

**Issue by paulvi** [protostuff/protostuff#204]
Could you add into README or wiki how to configure Eclipse to overcome issues like

> Plugin execution not covered by lifecycle configuration: io.protostuff:protostuff-maven-plugin:1.3.5:compile (execution: generate-sources, phase: generate-sources)

ref [SO](http://stackoverflow.com/questions/6352208/how-to-solve-plugin-execution-not-covered-by-lifecycle-configuration-for-sprin)

**Comment by kshchepanovskyi** [comment]
@dyu are you using Eclipse?

**Comment by dyu** [comment]
Yea I use eclipse but I don't use it's maven integration at all.
I just do mvn eclipse:eclipse and import the project that way.

**Comment by dyu** [comment]
Also when I compile my protos, I simply use a script that executes ```java -jar```

**Comment by paulvi** [comment]
Well, that can't be recommended solution for all.
My goal is that new developer can just check out project in IDE and start working on it, without any additional steps needed.

Result of this issue should be wiki page. Possibly with @dyu solution as well.

**Comment by dyu** [comment]
Added https://github.com/protostuff/protostuff#developing-with-eclipse
