### ISSUE TITLE
Got different serialize result after call String#hashCode method on String type.

### ISSUE THREAD

**Issue by eBoyy** [protostuff/protostuff#207]
I have debug and read the source code and found that `ProtostuffIOUtil` just use `RuntimeSchema#writeTo` to serialize a `String`.  
The Problem is that `RuntimeSchema#writeTo` just got all the fields of a `String` and then wrote them to the `Output` one by one. When I call the `String#hashCode` method, the filed `hash`  will change and then the serialize result will be different.

Is this a feature or bug?

Test code:

    import io.protostuff.LinkedBuffer;
    import io.protostuff.ProtostuffIOUtil;
    import io.protostuff.Schema;
    import io.protostuff.runtime.RuntimeSchema;
    import org.assertj.core.api.Assertions;
    
    import java.io.ByteArrayOutputStream;
    import java.io.IOException;
    
    public class Test {
    
        public static void main(String[] args) {
            String str = "key";
    
            byte[] beforeHash = serialize(str);
    
            // Call hashCode
            int hashCode = str.hashCode();
    
            byte[] afterHash = serialize(str);
    
            Assertions
                    .assertThat(beforeHash)
                    .isNotEqualTo(afterHash)
                    .as("Got different result after call hashCode");
        }
    
        private static <T> byte[] serialize(T obj) {
            Class<?> clazz = obj.getClass();
            @SuppressWarnings("unchecked")
            Schema<T> schema = (Schema<T>) RuntimeSchema.getSchema(clazz);
            LinkedBuffer buffer = LinkedBuffer.allocate(LinkedBuffer.DEFAULT_BUFFER_SIZE);
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            try {
                ProtostuffIOUtil.writeTo(bos, obj, schema, buffer);
                return bos.toByteArray();
            } catch (Exception e) {
                throw new RuntimeException("Serializing to a LinkedBuffer threw an IOException " +
                        "(should never happen).", e);
            } finally {
                buffer.clear();
                try {
                    bos.close();
                } catch (IOException ignored) {
                }
            }
        }
    }

**Comment by dyu** [comment]
Only call ```RuntimeSchema.getSchema``` on pojos.  Java's built-in primitive wrappers and String should **not** be passed to that method.

**Comment by eBoyy** [comment]
@dyu How about make it built in protostuff just like Kryo or Hessian?

**Comment by dyu** [comment]
Protostuff is based from protobuf, where you work against 'messages' a.k.a pojos.

If you want it to be general purpose, then use a wrapper object like the ```Wrapper.java``` in https://github.com/ryanemerson/infinispan-marshaller-protostuff/tree/master/src/main/java/org/infinispan/marshaller/protostuff
