### ISSUE TITLE
Can not correctly deserialize empty List

### ISSUE THREAD

**Issue by stream-iori** [protostuff/protostuff#219]
There is response from server side with protostuff, and there is empty ArrayList object in response.
we expect this ArrayList's size is 0, but get NPE.

**Comment by molp** [comment]
I have the same issue: I am trying to serialize an empty ArrayList and on deserialization I get null and a NPE after that. The NPE is in my code, that's fine, but I still expect an empty List after deserialization.

**Comment by dyu** [comment]
If you really want to null-protect your data objects transparently, the easiest thing to do is simply declare the fields like so:
```
private List<String> foo = new ArrayList<String>();
```

Other than that, that is the expected behavior.  If on serialization, no repeated field (list) gets serialized, that field on deser will not be touched at all.

**Comment by dyu** [comment]
See https://github.com/protostuff/protostuff/blob/master/protostuff-runtime/src/main/java/io/protostuff/runtime/RuntimeEnv.java for the instantiation options.

If you object has a zero-arg public contructor, by default protostuff will use that unless configured not do so.

**Comment by pli2014** [comment]
before run protostuff, set this config with static { System.setProperties("protostuff.runtime.allow_null_array_element", xx) }

**Comment by wenjuanhenxing** [comment]
You can use this scheme，an empty List after deserialization

`IdStrategy strategy = new DefaultIdStrategy(IdStrategy.DEFAULT_FLAGS | IdStrategy.COLLECTION_SCHEMA_ON_REPEATED_FIELDS ,null,0);
schema = RuntimeSchema.createFrom(originClazz, strategy);`

**Comment by dyu** [comment]
If you are to purely use this to replace java serialization (no compatibility with protobuf), set the following system properties:
```
-Dprotostuff.runtime.always_use_sun_reflection_factory=true
-Dprotostuff.runtime.preserve_null_elements=true
-Dprotostuff.runtime.morph_collection_interfaces=true
-Dprotostuff.runtime.morph_map_interfaces=true
-Dprotostuff.runtime.morph_non_final_pojos=true
```
