### ISSUE TITLE
RuntimeEnv#loadClass(String) cannot load class

### ISSUE THREAD

**Issue by Dico200** [protostuff/protostuff#223]
`RuntimeEnv#loadClass(String)` explicitly uses current thread's context classloader instead of `Class#forName`.

In my use case, where I have a polymorphic field, the class that I want to load is loaded on a separate class loader. As such, I'm unable to deserialize it in this context, because the class is not found on the thread's context class loader.

I created a hotfix library jar to depend on, and it fixed my issue.
Simply returning `Class.forName(name)` instead of the context class loader call in that method.

**Comment by Dico200** [comment]
In my use case, where I have a polymorphic field, the class that I want to load is loaded on a separate class loader. As such, I'm unable to deserialize it in this context, because the class is not found on the thread's context class loader.

**Comment by Dico200** [comment]
I created a hotfix library jar to depend on, and it fixed my issue.
Simply returning `Class.forName(name)` instead of the context class loader call in that method.

**Comment by kshchepanovskyi** [comment]
Seems that following change should fix the problem:

```diff
diff --git a/protostuff-runtime/src/main/java/io/protostuff/runtime/RuntimeEnv.java b/protostuff-runtime/src/main/java/io/protostuff/runtime/RuntimeEnv.java
index afd71d0..ec4c04b 100644
--- a/protostuff-runtime/src/main/java/io/protostuff/runtime/RuntimeEnv.java
+++ b/protostuff-runtime/src/main/java/io/protostuff/runtime/RuntimeEnv.java
@@ -252,7 +252,11 @@ public final class RuntimeEnv
         }
         catch (ClassNotFoundException e)
         {
-            throw new RuntimeException(e);
+            try {
+                return (Class<T>) Class.forName(className);
+            } catch (ClassNotFoundException e1) {
+                throw new RuntimeException(e);
+            }^M
         }
     }
```

**Comment by kshchepanovskyi** [comment]
However, I will need a unit test in order to reproduce problem and test the fix. If you can provide one - I can apply the fix and make new release immediately.

**Comment by Dico200** [comment]
The reason why this is necessary should be fairly straightforward from the previous title, but, sure, I'll try to recreate the conditions under which this error occurs.

**Comment by Dico200** [comment]
At second thought, a simple unit test is not going to be possible to demonstrate this issue. It requires a jar file to be loaded onto the classpath with a custom class loader. 

In my use case, the jar file is a plugin that provides a subclass of a polymorphic field. When the RuntimeEnv.loadClass call comes around to get the class object, it's not found by the context class loader.

**Comment by Dico200** [comment]
One option for a unit test would be to run code on a thread with a custom context class loader, but that wouldn't give the same conditions under which the error was a problem for me.

**Comment by Dico200** [comment]
I will give you the key classes that make the error happen and provide the conditions that are required.

I have this class here to serialize a polymorphic object (simplified):

```
import io.protostuff.Schema;
import io.protostuff.Tag;
import io.protostuff.runtime.RuntimeSchema;

public abstract class SerializationRoot {
    
    @Tag(1)
    private String typeId;
    
    public static SerializationRoot deserialize(byte[] data) {
        ...
    }
    
    public static byte[] serialize(SerializationRoot value) {
        ...
    }
    
    public static class Wrapper {
        public static final Schema<Wrapper> SCHEMA = RuntimeSchema.getSchema(Wrapper.class);
        
        @Tag(1)
        private SerializationRoot value;
        
    }
    
}
```

There is a driver that manages the type providers, each type has a typeId.
A type provider is loaded from another jar file, using a custom class loader.
It registers itself with the driver.

The type provides a subclass of the `SerializationRoot`, adding additional fields
And it saves it to a global file.

When deserializing, the RuntimeEnv#loadClass(String) method looks for the subclass on the thread's context class loader, which has no information about the jar file that was loaded on a separate class loader, and the call fails.

**Comment by Dico200** [comment]
In the change you provided, instead of `throw new RuntimeException(e)`, 
shouldn't you 
```
e1.addSuppressed(e);
throw new RuntimeException(e1);
```
?

**Comment by kshchepanovskyi** [comment]
There is no difference in this case. First exception does not provide any additional information that is not already present in the second one.

**Comment by kshchepanovskyi** [comment]
Released version 1.5.6

**Comment by Dico200** [comment]
Cool, thank you for taking my word and explanation and not requiring the test case, which as I explained, I have no clue how to write as a single class.

**Comment by kshchepanovskyi** [comment]
I tried to create a test myself, but eventually I gave up :)
