### ISSUE TITLE
a bug when deserialize an object contains a singleton

### ISSUE THREAD

**Issue by leizhiyuan** [protostuff/protostuff#236]
below, It is the test case. you can see, Currency.getInstance("CNY") =USD

```
public class SecTest {

    public static void main(String[] t) {

        SimpleObject simpleObject = null;
        byte[] bytes;
        simpleObject = new SimpleObject(Currency.getInstance("USD"));

        LinkedBuffer buffer = LinkedBuffer.allocate(1024);

        Schema<SimpleObject> schema = RuntimeSchema.getSchema(SimpleObject.class);

        bytes = ProtobufIOUtil.toByteArray(simpleObject, schema, buffer);

        SimpleObject val = schema.newMessage();
        ProtobufIOUtil.mergeFrom(bytes, val, schema);

        Assert.assertEquals("CNY", Currency.getInstance("CNY").getCurrencyCode());
    }

    public static class SimpleObject {

        private Currency currency;

        public SimpleObject() {
            this.currency = Currency.getInstance("CNY");
        }

        public SimpleObject(Currency currency) {
            this.currency = currency;
        }

        public Currency getCurrency() {
            return currency;
        }

        public void setCurrency(Currency currency) {
            this.currency = currency;
        }
    }
}
```

**Comment by dyu** [comment]
For singletons, you could use a [delegate](http://www.protostuff.io/documentation/runtime-schema-delegate/) to workaround that.

They would written as a string on the wire.

**Comment by leizhiyuan** [comment]
@dyu  I got it, But does It mean that we need to find all the singletons in our code, then registerDelegate them. including the third Class or some classes in jdk that we use?

**Comment by dyu** [comment]
@leizhiyuan If it is really a singleton (only 1 instance), then you just have to use GraphIOUtil.
For these special classes (Currency) that are not really singleton but have limited instances, you register a delegate for every one of them.
As a bonus, if you control/know all the data and have singletons, you can avoid using GraphIOUtil and instead simply register a delegate for them.

**Comment by leizhiyuan** [comment]
@dyu Thank you , We will find the classes which need to be serialized and deserialized
, and  try to register a delegate  for the 'singleton' class there, Thank you again.
