### ISSUE TITLE
Can't find the server IP address of www.protostuff.io

### ISSUE THREAD

**Issue by eawaun** [protostuff/protostuff#241]
Maybe it is overdue?

**Comment by dyu** [comment]
It is.
@kshchepanovskyi had been managing the domain and its [contents](https://github.com/protostuff/protostuff.github.io) for the past 3 years.

I shall move the contents to https://dyuproject.com/protostuff/ and update the links since it looks like he does not want to maintain it anymore.

**Comment by dyu** [comment]
Moved to https://protostuff.github.io
