### ISSUE TITLE
About array object contains null index misplaced problem

### ISSUE THREAD

**Issue by fenghuaxz** [protostuff/protostuff#243]
Same topic:

Object[] objs = new Object[]{"1",null,"3"};

Deserialization results:

Objs[0] = "1"
Objs[1] = "3"
Objs[2] = null

After modifying the following code(Tested to solve the problem):

![dk1 bs2 zx ahdaix 7yj6](https://user-images.githubusercontent.com/14834603/38435629-ca8f9358-3a04-11e8-93f7-738487132c09.png)
![_6 dyn9 etery p 1v0 hd](https://user-images.githubusercontent.com/14834603/38435642-d6ec9876-3a04-11e8-8387-1ce9882b9b29.png)
![p ht1hp_j _ o08fn rw2m](https://user-images.githubusercontent.com/14834603/38435653-e0fb0960-3a04-11e8-92bc-7324f2fe5e2f.png)
![bt3w 8z45d og1p zgry nk](https://user-images.githubusercontent.com/14834603/38435755-46068a64-3a05-11e8-988b-16f3d0d0a0c2.png)

**Comment by fenghuaxz** [comment]
@dyu Thanks

**Comment by MIMIEYES** [comment]
@dyu I have set the system property: `-Dprotostuff.runtime.allow_null_array_element=true`
One-dimensional array can work, but two-dimensional array do not work.

```java
String[][] args = new String[][]{{"NseKznzD5fTe7LyrSa365Rko8UKmCE17"}, null, null, {"0"}};
```
Deserialization results:
[NseKznzD5fTe7LyrSa365Rko8UKmCE17]
[0]
[]
[]

**Comment by dyu** [comment]
Fixed in master.
You can currently test with 1.8.0-SNAPSHOT
Use:
`-Dprotostuff.runtime.preserve_null_elements=true`
It applies to both collections and arrays
