### ISSUE TITLE
How to keep fields in the same order in different jvms?

### ISSUE THREAD

**Issue by teaey** [protostuff/protostuff#244]
Method
```
Class.getDeclaredFields()
```
The elements in the returned array are not sorted and are not in any particular order.

How to keep fields in the same order in different jvms?

**Comment by dyu** [comment]
They are sorted in declaration order on sun/oracle/openjdk jvms.
On android (dalvik) this is a problem.  This is documented in https://protostuff.github.io/docs/protostuff-runtime/

The solution in that link is to simply explicitly tag your fields.

**Comment by teaey** [comment]
Got it.

Thanks.

https://protostuff.github.io/docs/protostuff-runtime/
