### ISSUE TITLE
RuntimeEnv.ALLOW_NULL_ARRAY_ELEMENT is invalid for IdStrategy#ARRAY_STRING_SCHEMA

### ISSUE THREAD

**Issue by fengjiachun** [protostuff/protostuff#251]
RuntimeEnv.ALLOW_NULL_ARRAY_ELEMENT is invalid for IdStrategy#ARRAY_STRING_SCHEMA.
IdStrategy#ARRAY_STRING_SCHEMA is always constructed before IdStrategy#flags is initialized, which causes IdStrategy#ARRAY_STRING_SCHEMA#allowNullArrayElement to be always false

**Comment by fengjiachun** [comment]
I covered the IdStrategy class in my own project. If you think this fix is OK, may I send a pr?

**Comment by dyu** [comment]
Please do send a PR.  Thanks in advance @fengjiachun
