### ISSUE TITLE
Proto3 support

### ISSUE THREAD

**Issue by Kavyamanjanatha** [protostuff/protostuff#254]
I see that Protostuff is supporting only proto2 .
What shoudl be done to support proto 3

**Comment by yellowbigbird** [comment]
agree.
did a test, protostuff 1.6.0 can't be compatible with protobuf 3.7.0.
The binary output is not same.

**Comment by yellowbigbird** [comment]
hi, @Kavyamanjanatha , Please try ProtobufIOUtil.

**Comment by yellowbigbird** [comment]
And still found map support issue.
binary serialized by protobuf class, can't deserialized by protostuff.

**Comment by wujimin** [comment]
about compatible
there is a comparison in https://github.com/apache/servicecomb-java-chassis/tree/master/foundations/foundation-protobuf

**Comment by yellowbigbird** [comment]
Thx, have tried foundation-protobuf, still failed on binary compatible test.

**Comment by wujimin** [comment]
can you please submit a issue in https://github.com/apache/servicecomb-java-chassis/issues, and provide a reproducer? 
thanks.

**Comment by yellowbigbird** [comment]
I'll try.

**Comment by yellowbigbird** [comment]
add issue https://github.com/apache/servicecomb-java-chassis/issues/1217
but been ignored.

**Comment by promiselonely** [comment]
Have you tried version 1.7.2? Will it work?

**Comment by philipwhiuk** [comment]
No it doesn't:

https://github.com/protostuff/protostuff/blob/c35583dfce3121fb793a2e0116f31708cd5293ad/protostuff-parser/src/main/antlr3/io/protostuff/parser/ProtoParser.g#L134

**Comment by kshchepanovskyi** [comment]
https://github.com/protostuff/protostuff-compiler/search?q=proto3
