### ISSUE TITLE
protostuff serialization problem with emoj string

### ISSUE THREAD

**Issue by pisces-djl** [protostuff/protostuff#262]
Once I used protostuff to serialization an Object and then unSerialize the bytes， when a String property contained emoj (such as  😄 😁😢...) in the object， after unSerialized， the results was uncertain.
 In my local machine, it works well, While in out test environment, it was converted to error codes，（such as ？？）；
Do you meet it， why？

**Comment by dyu** [comment]
Make sure the test environment have the same version of protostuff and jvm versions.
E.g. Make sure protostuff 1.5.x is used on the machine with a java 8 virtual machine.

**Comment by pisces-djl** [comment]
> Make sure the test environment have the same version of protostuff and jvm versions.
> E.g. Make sure protostuff 1.5.x is used on the machine with a java 8 virtual machine.

oh，the version of  protostuff I used  is  1.0.12， After I change the jdk version to 1.8 （the same as our test environment ）in my local development environment， it was converted to error codes，too.

I wonder the detail reason, do you know ?

**Comment by dyu** [comment]
java 8 internally changed its utf8 decoding scheme from java 7 and below.  The 1.5.x and later releases handles those breaking jvm changes internally too.

**Comment by dyu** [comment]
If you try protostuff 1.1.x with a java 7 runtime on both your machines, that would work too (in case you're curious).

**Comment by PeppaLittlePig** [comment]
hi , i want to konw why "com.dyuproject.protostuff" this groupid still have this bug until latest version 1.1.3 , and what is relation between "com.dyuproject.protostuff"   and "io.protostuff"?

**Comment by dyu** [comment]
For 1.1.3 and below, use java 7.   If you are using java 8 and above, use io.protostuff (later versions).  Java 8 had an internal change of how it decodes utf8 (backwards incompatible)

**Comment by PeppaLittlePig** [comment]
If our projects ues java 7 & 8, and our common module use io.protostuff version 1.5.9 ,can it run normally in different environments?

**Comment by dyu** [comment]
Yes. Always use 1.5.x or 1.6.x if you mix java 7/8 usage
