### ISSUE TITLE
NullPointerException with Map<String, whatever[]>

### ISSUE THREAD

**Issue by trebonius0** [protostuff/protostuff#264]
Hello

I've been using latest version (1.6.0) of protostuff and today I noticed a NullPointerException when deserializing an object containing Map<String, whatever[]>.
I include in my project all those: 
![image](https://user-images.githubusercontent.com/14201457/54675496-fc816d80-4afe-11e9-8177-8044dc903946.png)

Here is the test code to reproduce the issue;

```
public class MyTest {

    public static class AA {

        public Map<String, BB[]> map;

    }

    public static class BB {

        public long bb1;
        public long bb2;

        public BB() {
        }

        public BB(long bb1, long bb2) {
            this.bb1 = bb1;
            this.bb2 = bb2;
        }

    }

    @Test
    public void test() {
        AA aa = new AA();
        aa.map = new HashMap<>();
        aa.map.put("o1", new BB[]{new BB(1, 2), new BB(3, 4), new BB(5, 6)});
        aa.map.put("o2", new BB[]{new BB(10, 11)});

        LinkedBuffer buffer = LinkedBuffer.allocate(4096);
        Schema<AA> schema = RuntimeSchema.getSchema(AA.class);
        byte[] protostuff = null;
        try {
            protostuff = ProtostuffIOUtil.toByteArray(aa, schema, buffer);
        } finally {
            buffer.clear();
        }

        AA result = schema.newMessage();
        ProtostuffIOUtil.mergeFrom(protostuff, result, schema);

        Assert.assertEquals(aa.map.size(), result.map.size());
        Assert.assertEquals(aa.map.get("o1").length, result.map.get("o1").length);
        Assert.assertEquals(aa.map.get("o2").length, result.map.get("o2").length);
    }
}
```

This also happens when I'm not using embedded classes. 

The stack trace is

> 
> java.lang.NullPointerException
> java.lang.RuntimeException
> 	at io.protostuff.runtime.RuntimeMapFieldFactory$5.mergeFrom(RuntimeMapFieldFactory.java:508)
> 	at io.protostuff.runtime.RuntimeSchema.mergeFrom(RuntimeSchema.java:466)
> 	at io.protostuff.IOUtil.mergeFrom(IOUtil.java:45)
> 	at io.protostuff.ProtostuffIOUtil.mergeFrom(ProtostuffIOUtil.java:104)
> 	at common.MyTest.test(MyTest.java:52)
> 	at io.protostuff.runtime.ArraySchemas$Base.setValue(ArraySchemas.java:320)
> 	at io.protostuff.runtime.ArraySchemas$Base.mergeFrom(ArraySchemas.java:326)
> 	at io.protostuff.ByteArrayInput.mergeObjectEncodedAsGroup(ByteArrayInput.java:518)
> 	at io.protostuff.ByteArrayInput.mergeObject(ByteArrayInput.java:490)
> 	at io.protostuff.runtime.RuntimeMapFieldFactory$5.vPutFrom(RuntimeMapFieldFactory.java:563)
> 	at io.protostuff.runtime.RuntimeMapField$1.putValueFrom(RuntimeMapField.java:61)
> 	at io.protostuff.MapSchema$2.mergeFrom(MapSchema.java:493)
> 	at io.protostuff.MapSchema$2.mergeFrom(MapSchema.java:388)
> 	at io.protostuff.ByteArrayInput.mergeObjectEncodedAsGroup(ByteArrayInput.java:518)
> 	at io.protostuff.ByteArrayInput.mergeObject(ByteArrayInput.java:490)
> 	at io.protostuff.MapSchema.mergeFrom(MapSchema.java:334)
> 	at io.protostuff.MapSchema.mergeFrom(MapSchema.java:31)
> 	at io.protostuff.ByteArrayInput.mergeObjectEncodedAsGroup(ByteArrayInput.java:518)
> 	at io.protostuff.ByteArrayInput.mergeObject(ByteArrayInput.java:490)
> 	at io.protostuff.runtime.RuntimeMapFieldFactory$5.mergeFrom(RuntimeMapFieldFactory.java:503)
> 

Could you help me with that ?

Thanks

**Comment by dyu** [comment]
Thanks for reporting.  This was overlooked (Arrays not usually used in values) but yea, no excuses :-) 
Fixed via https://github.com/protostuff/protostuff/commit/03d641a93950ace885854bd38e332ab7aab12021

**Comment by trebonius0** [comment]
Thanks ! 
Do you know when the release with the fix will be available ?

**Comment by txzh** [comment]
I have encountered this issue recently, you can use List to replace array to circumvent it
