### ISSUE TITLE
stackoverflow when serializing an object with list

### ISSUE THREAD

**Issue by Moriadry** [protostuff/protostuff#269]
I met stackoverflow when pass an object with arraylist, code is as blew:

```
  List<SerializablePerson> list = new ArrayList<SerializablePerson>();

        list.add(new SerializablePerson());
        list.add(new SerializablePerson());
        list.add(new SerializablePerson());

       PersonList obj = new PersonList(list);

       Schema schema = RuntimeSchema.getSchema(obj.getClass());
// both two toByteArray method will cause stackoverflow.
       bytes = GraphIOUtil.toByteArray(obj, schema, buffer);
       bytes = ProtobufIOUtil.toByteArray(obj, schema, buffer);
       classNameBytes = obj.getClass().getName().getBytes();

```

Was it  wrong about the usage?

**Comment by dyu** [comment]
Can you post/attach an example that triggers the stackoverflow?

**Comment by Moriadry** [comment]
import io.protostuff.LinkedBuffer;
import io.protostuff.ProtobufIOUtil;
import io.protostuff.Schema;
import io.protostuff.runtime.RuntimeSchema;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.io.*;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.List;

public class Demo {

    private ByteArrayOutputStream byteArrayOutputStream;
    private ProtostuffObjectOutput protostuffObjectOutput;

    @BeforeEach
    public void setUp() throws Exception {
        this.byteArrayOutputStream = new ByteArrayOutputStream();
        this.protostuffObjectOutput = new ProtostuffObjectOutput(byteArrayOutputStream);
    }

    @Test
    public void test() throws IOException {
        LocalTimeList list = generateObject();

        this.protostuffObjectOutput.writeObject(list);
    }

    private LocalTimeList generateObject() {
        List<LocalTime> list = new ArrayList<LocalTime>();

        LocalTime localTime = LocalTime.parse("12:00:00");
        LocalTime localSecondTime = LocalTime.parse("13:00:00");
        LocalTime localThirdTime = LocalTime.parse("14:00:00");
        list.add(localTime);
        list.add(localSecondTime);
        list.add(localThirdTime);

        return new LocalTimeList(list);
    }

    private class LocalTimeList implements Serializable {
        private static final long serialVersionUID = 1L;

        List<LocalTime> list;

        public LocalTimeList() {}

        public LocalTimeList(List<LocalTime> list) {
            this.list = list;
        }
    }

    private class ProtostuffObjectOutput {

        LinkedBuffer buffer = LinkedBuffer.allocate();

        private DataOutputStream dos;

        public ProtostuffObjectOutput(OutputStream outputStream) {
            dos = new DataOutputStream(outputStream);
        }

        public void writeObject(Object obj) throws IOException {

            byte[] bytes;
            byte[] classNameBytes;

            try {
                    Schema schema = RuntimeSchema.getSchema(obj.getClass());
                    bytes = ProtobufIOUtil.toByteArray(obj, schema, buffer);
                    classNameBytes = obj.getClass().getName().getBytes();
            } finally {
                buffer.clear();
            }
            dos.writeInt(classNameBytes.length);
            dos.writeInt(bytes.length);
            dos.write(classNameBytes);
            dos.write(bytes);
        }
    }
}

**Comment by Moriadry** [comment]
import io.protostuff.LinkedBuffer;
import io.protostuff.ProtobufIOUtil;
import io.protostuff.Schema;
import io.protostuff.runtime.RuntimeSchema;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.io.*;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.List;

public class Demo {

    private ByteArrayOutputStream byteArrayOutputStream;
    private ProtostuffObjectOutput protostuffObjectOutput;

    @BeforeEach
    public void setUp() throws Exception {
        this.byteArrayOutputStream = new ByteArrayOutputStream();
        this.protostuffObjectOutput = new ProtostuffObjectOutput(byteArrayOutputStream);
    }

    @Test
    public void test() throws IOException {
        LocalTimeList list = generateObject();

        this.protostuffObjectOutput.writeObject(list);
    }

    private LocalTimeList generateObject() {
        List<LocalTime> list = new ArrayList<LocalTime>();

        LocalTime localTime = LocalTime.parse("12:00:00");
        LocalTime localSecondTime = LocalTime.parse("13:00:00");
        LocalTime localThirdTime = LocalTime.parse("14:00:00");
        list.add(localTime);
        list.add(localSecondTime);
        list.add(localThirdTime);

        return new LocalTimeList(list);
    }

    private class LocalTimeList implements Serializable {
        private static final long serialVersionUID = 1L;

        List<LocalTime> list;

        public LocalTimeList() {}

        public LocalTimeList(List<LocalTime> list) {
            this.list = list;
        }
    }

    private class ProtostuffObjectOutput {

        LinkedBuffer buffer = LinkedBuffer.allocate();

        private DataOutputStream dos;

        public ProtostuffObjectOutput(OutputStream outputStream) {
            dos = new DataOutputStream(outputStream);
        }

        public void writeObject(Object obj) throws IOException {

            byte[] bytes;
            byte[] classNameBytes;

            try {
                    Schema schema = RuntimeSchema.getSchema(obj.getClass());
                    bytes = ProtobufIOUtil.toByteArray(obj, schema, buffer);
                    classNameBytes = obj.getClass().getName().getBytes();
            } finally {
                buffer.clear();
            }
            dos.writeInt(classNameBytes.length);
            dos.writeInt(bytes.length);
            dos.write(classNameBytes);
            dos.write(bytes);
        }
    }
}

**Comment by Moriadry** [comment]
@dyu  hi, you can run a demo test like this. This will show a stackoverflow, and it shows that, it will call `public final void writeTo(Output output, T message)` of `RuntimeSchema.class`

**Comment by dyu** [comment]
Mark it static: ```private static class LocalTimeList```

**Comment by Moriadry** [comment]
Thanks!
