### ISSUE TITLE
Why not provide a unified util class to process non-loop-reference object and loop-reference object

### ISSUE THREAD

**Issue by tswstarplanet** [protostuff/protostuff#270]
Now protostuff provide ProtobufIOUtil to process non-loop-reference object, and GraphIOUtil to process loop-reference object. I think it's a bad design because users usually cannot determine if a object to be processed is a loop-reference object, it will be determined in runtime, so he/she can not decide to use which one of the two class.

**Comment by dyu** [comment]
In that case, always use GraphIOUtil.  There is overhead but that is the price you pay for not knowing the structure of the data in advance.
