### ISSUE TITLE
A way to not write metadata for an abstract class, and instead use a concrete type?

### ISSUE THREAD

**Issue by ChrisTrenkamp** [protostuff/protostuff#271]
I am using [Immutables](https://immutables.github.io/immutable.html) in my project, and am using Protostuff to serialize/deserialize the generated Immutable classes.

The [performance guidelines](https://protostuff.github.io/docs/protostuff-runtime/#-performance-guidelines-) say to use concrete classes whenever possible, otherwise it will have to write out the class metadata when serializing the object, possibly affecting performance.

In my project, I'm reducing the visibility of the concrete, Immutable classes to the package level to keep the project clean.  However, this will mean that whenever I serialize an object that contains an abstract Immutable definition, the metadata needs to be written out for that field.  This may turn into a problem because I'm adding a lot of Immutable class definitions in this project.

Right now, I'm using the DefaultIdStrategy class.  If the performance starts becoming affected due to all the metadata being written, I can switch to the ExplicitIdStrategy class and generate an integer ID based on a hash of the FQDN (or explicitly set an ID if there's a hash collision).  However, the ideal scenario would be to instruct Protostuff to, for Immutable classes, not write the metadata for the abstract class, and instead use the concrete type.  Is there a way to do this?

I haven't done any benchmarks yet, so I don't know if the performance will be affected, but I'd like to be prepared if it is.

**Comment by dyu** [comment]
> However, the ideal scenario would be to instruct Protostuff to, for Immutable classes, not write the metadata for the abstract class, and instead use the concrete type. Is there a way to do this?

``` RuntimeSchema.map(abstractClass, concretClass); ```
