### ISSUE TITLE
How does it support nested collections like Map<String,Map>

### ISSUE THREAD

**Issue by sk1188** [protostuff/protostuff#276]
As per Protocol Buffer documentation, they do not support nested collections like Map<String,Map> , List<String, Map> in .proto schema definition file.
Also, default values for string is "" and for numeric types is 0.

So, my query is  does ProtoStuff serialization/de-serialization also has these limitations mentioned above?

If not, then how does it work because as per my understanding it uses protobuffers internally ?

**Comment by dyu** [comment]
Protostuff does not have the limitations above.  If you stick with what's supported in official protobuf, it is compatible with protostuff on the wire.
