### ISSUE TITLE
nulls silently dropped even when using "protostuff.runtime.allow_null_array_element"

### ISSUE THREAD

**Issue by mikaelgrev** [protostuff/protostuff#281]
I don´t understand why these two produce different results.
```java
static final class Foo
{
	Object o;
	Foo(Object o)
	{
		this.o = o;
	}
}

public static void main(String[] args)
{
	System.setProperty("protostuff.runtime.allow_null_array_element", "true");

	System.out.println("Serializing an ArrayList<String>:");
	roundTrip(true);
	System.out.println("\nSerializing a String[]:");
	roundTrip(false);
}

static void roundTrip(boolean bug)
{
	LinkedBuffer buffer = LinkedBuffer.allocate(512);

	Foo bef = bug ? new Foo(new ArrayList(Arrays.asList("1", null, "2"))) : new Foo(new String[]{"1", null, "2"});

	Schema<Foo> schema = RuntimeSchema.getSchema(Foo.class);

	byte[] bytes = ProtostuffIOUtil.toByteArray(bef, schema, buffer);
	buffer.clear();

	Foo aft = schema.newMessage();
	ProtostuffIOUtil.mergeFrom(bytes, aft, schema);

	if (bug) {
		System.out.println("Before: " + bef.o);
		System.out.println("After : " + aft.o);
		System.out.println("Set   : " + RuntimeEnv.ALLOW_NULL_ARRAY_ELEMENT);
	} else {
		System.out.println("Before: " + Arrays.toString((String[]) bef.o));
		System.out.println("After : " + Arrays.toString((String[]) aft.o));
		System.out.println("Set   : " + RuntimeEnv.ALLOW_NULL_ARRAY_ELEMENT);
	}
}
```

The output is:

Serializing an ArrayList<String>:
Before: [1, null, 2]
After : [1, 2]
Set   : true

Serializing a String[]:
Before: [1, null, 2]
After : [1, null, 2]
Set   : true

Notice how the null is silently dropped in the first output.

I have tried this with 1.6.2 and 1.7.2

**Comment by dyu** [comment]
That is the limitation.  Protostuff does not serialize any null value.  It's output was byte-for-byte compatible with protobuf (ProtobufIOUtil) when you use List<T> for repeated fields.
I added the functionality to serialize null on arrays only, as it was requested by users.

**Comment by mikaelgrev** [comment]
Ah, OK.
So basically it matters if the array is a field in a List or if it is a field in an object that is not a List?

**Comment by mikaelgrev** [comment]
I am also a bit puzzled why these two cases differers. The only difference is the type of the array.
```java
static final class Foo
{
	Object o;
	Foo(Object o)
	{
		this.o = o;
	}
}

public static void main(String[] args)
{
	System.setProperty("protostuff.runtime.allow_null_array_element", "true");

	System.out.println("Serializing an ArrayList<String>:");
	roundTrip(true);
	System.out.println("\nSerializing a String[]:");
	roundTrip(false);
}

static void roundTrip(boolean bug)
{
	LinkedBuffer buffer = LinkedBuffer.allocate(512);

	Foo bef = bug ? new Foo(new Object[]{"1", null, "2"}) : new Foo(new String[]{"1", null, "2"});

	Schema<Foo> schema = RuntimeSchema.getSchema(Foo.class);

	byte[] bytes = ProtostuffIOUtil.toByteArray(bef, schema, buffer);
	buffer.clear();

	Foo aft = schema.newMessage();
	ProtostuffIOUtil.mergeFrom(bytes, aft, schema);

	System.out.println("Before: " + Arrays.toString((Object[]) bef.o));
	System.out.println("After : " + Arrays.toString((Object[]) aft.o));
	System.out.println("Set   : " + RuntimeEnv.ALLOW_NULL_ARRAY_ELEMENT);
}
```

Produces the output (on both 1.6.2 and 1.7.2):

Serializing an Object[]:
Before: [1, null, 2]
After : [1, 2, null]
Set   : true

Serializing a String[]:
Before: [1, null, 2]
After : [1, null, 2]
Set   : true

I thought I saw a fix for this that should be in.

**Comment by dyu** [comment]
Thinking about it, protostuff can be refactored to serialize null on collections and maps via a flag.
If that flag is not set, it will default to the current behavior.
It's the best of both worlds ... the java folks would get to keep their nulls and those that don't would exclude them.
It's a big refactor. I've no guarantees when it will be implemented since I'm pretty busy nowadays.

**Comment by mikaelgrev** [comment]
That would be great! This "anomaly" in Java-esque null handling is the only thing that sticks out in this otherwise fantastic library.

**Comment by dyu** [comment]
> That would be great! This "anomaly" in Java-esque null handling is the only thing that sticks out in this otherwise fantastic library.

Yea.  My use-case was different initially when I created this lib.  But then the users wanted more functionality and I gradually implemented them as they came in, without thinking that this could be a *generic* serialization lib :-)

WIth the proposed changes, any container (array, collection, map) would always have their nulls always serialized, via a flag.

**Comment by dyu** [comment]
> That would be great! This "anomaly" in Java-esque null handling is the only thing that sticks out in this otherwise fantastic library.

Yea.  My use-case was different initially when I created this lib.  But then the users wanted more functionality and I gradually implemented them as they came in, without thinking that this could be a *generic* serialization lib :-)

WIth the proposed changes, any container (array, collection, map) would always have their nulls always serialized, via a flag.

**Comment by dyu** [comment]
Fixed in master.
You can currently test with 1.8.0-SNAPSHOT
Use:
`-Dprotostuff.runtime.preserve_null_elements=true`
It applies to both collections and arrays

**Comment by mikaelgrev** [comment]
Tried both cases i posted above with 1.8.0-SNAPSHOT with the new flag and they both now work just as I expect them would. Thanks, and good job!
