### ISSUE TITLE
DefaultIdStrategy example on home page documentation doesn't compile

### ISSUE THREAD

**Issue by jon-hanson** [protostuff/protostuff#282]
This example from the [documentation](https://github.com/protostuff/protostuff#important):

```
static final DefaultIdStrategy STRATEGY = new DefaultIdStrategy(IdStrategy.DEFAULT_FLAGS 
        | IdStrategy.PRESERVE_NULL_ELEMENTS,
        | IdStrategy.MORPH_COLLECTION_INTERFACES,
        | IdStrategy.MORPH_MAP_INTERFACES,
        | IdStrategy.MORPH_NON_FINAL_POJOS);
```

doesn't compile using the latest released version (1.7.2). It appears to have extraneous commas, and the IdStrategy class does not have a field called PRESERVE_NULL_ELEMENTS.

**Comment by mirlord** [comment]
https://github.com/protostuff/protostuff/pull/288 fixes syntax (removes unnecessary commas).

Speaking of a new option name (`PRESERVE_NULL_ELEMENTS` replaces `ALLOW_NULL_ARRAY_ELEMENT`) - I don't think it makes sense to address that. README is an inherent part of a source tree, but not a standalone document. Even though we all use it this way :-)
