### ISSUE TITLE
JVM core dump while serializing a custom Map with out KEY declaring

### ISSUE THREAD

**Issue by squallud** [protostuff/protostuff#283]
public class TmpHashMap\<E extends Table\> extends HashMap\<String, E\>
{
    private final boolean finished = false;
}

public class Table
{
    int id = 0;
    String name = "tbl";
}

public class TmpMapWrapper
{
    TmpHashMap\<Table\> tmpHashMap = new TmpHashMap(){{put("hello", new Table());}};
}

While serializing the instance of TmpMapWrapper, it will cause jvm core dump. I think that protostuff treat the Type of value as the Type of key.

How can I serialize the TmpMapWrapper class in this case?

**Comment by dyu** [comment]
What version are you using? 1.7.2?

**Comment by squallud** [comment]
> What version are you using? 1.7.2?

My version using is 1.6.0; Had it been solved in 1.7.2?

**Comment by dyu** [comment]
Yes it has been fixed in 1.7.2

**Comment by squallud** [comment]
OK, That's really good. I will try the latest version. Thank you
