### ISSUE TITLE
ProtoStuff serialize some data may cause jvm crash,and cannot be caught

### ISSUE THREAD

**Issue by lasting0001** [protostuff/protostuff#309]
**protostuff:** 
1.7.0

**jdk:** 
Java HotSpot(TM) 64-Bit Server VM (build 25.202-b08, mixed mode)

**system:** 
Microsoft Windows 10 Enterprise 10.0.19041 19041

**idea:**
IntelliJ IDEA 2018.3.5 (Ultimate Edition)
Build #IU-183.5912.21, built on February 26, 2019

**code:** 

    public static void main(String[] args) {
        TestMsg testMsg = new TestMsg();
        List decals = new ArrayList<>();
        decals.add(1);
        testMsg.decal = decals;// force set different type data

        Schema schema = RuntimeSchema.getSchema(testMsg.getClass());
        byte[] bytes = ProtostuffIOUtil.toByteArray(testMsg, schema, LinkedBuffer.allocate());
        System.err.println(Arrays.toString(bytes));
    }

    private static class TestMsg {
        @Tag(1)
        public int tid;
        @Tag(2)
        public List<DecalMsg> decal;
    }

    private static class DecalMsg {
        @Tag(1)
        public int tid;
        @Tag(2)
        public PointMsg point;
    }

    private static class PointMsg {
        @Tag(1)
        public int x;
        @Tag(2)
        public int y;
        @Tag(3)
        public int z;
    }

**crash log:**
[hs_err_pid12056.log](https://github.com/protostuff/protostuff/files/6008758/hs_err_pid12056.log)

**my analysis:**
this problem was caused by this line:
testMsg.decal = decals;// force set different type data

**my hope:**
if the data type is wrong,make it caught by try-catch(Throwable e){}.
jvm crash is not recommended. it may be under attack at any time, and cause great financial losses

**thanks  for ur attention...**

**Comment by lasting0001** [comment]
Hi there...

**Comment by dyu** [comment]
Sorry for the late reply. I was able to replicate this.
Fixed in master (https://github.com/protostuff/protostuff/commit/4c3eccedb4c0e1220451509735a280a833f92239)
Will backport fix to 1.7.x

**Comment by dyu** [comment]
I've released 1.7.3 that fixes this issue. It should be available in the maven repos shortly

**Comment by lasting0001** [comment]
Thanks a lot, it throw a RuntimeException now~

**Comment by lasting0001** [comment]
Thanks a lot, it throw a RuntimeException now~
