### ISSUE TITLE
Release v1.8.0 please

### ISSUE THREAD

**Issue by dblock** [protostuff/protostuff#327]
We are using protostuff in OpenSearch/anomaly-detection and are looking to fix https://github.com/opensearch-project/anomaly-detection/issues/263. Looks like it's https://github.com/protostuff/protostuff/issues/239 and is at least partially fixed in https://github.com/protostuff/protostuff/commit/b6ad96f229218a835ec3f7232fa8ee129a6d3806. 

Can the maintainers please cut a release? Much appreciated, let us know if/how we can help.

**Comment by dyu** [comment]
@dblock @ylwu-amzn Can you try `<version>1.8.0-SNAPSHOT</version>` and see if you encounter issues?  It is based on latest master. 
If you don't encounter any issues relating to java 17/etc, then a release will follow shortly.

**Comment by dblock** [comment]
Is there a maven repository where 1.8.0-SNAPSHOT is published or should I be building it? Can't seem to resolve it from anywhere.

**Comment by dyu** [comment]
@dblock Snapshots need to be enabled in your maven repo config. Smoething like:
```xml
       <repository>
         <id>snapshots-repo</id>
         <url>https://oss.sonatype.org/content/repositories/snapshots</url>
         <releases><enabled>false</enabled></releases>
         <snapshots><enabled>true</enabled></snapshots>
       </repository>
```

**Comment by dyu** [comment]
1.8.0 released. It should be available in the maven repos shortly.
thanks @dblock

**Comment by idelac3** [comment]
Tested with **1.8.0**, this is what I see in the console:

`WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by io.protostuff.runtime.EnumIO (file:/home/idelac/.m2/repository/io/protostuff/protostuff-runtime/1.8.0/protostuff-runtime-1.8.0.jar) to field java.util.EnumMap.keyType
WARNING: Please consider reporting this to the maintainers of io.protostuff.runtime.EnumIO
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
`

**Comment by dblock** [comment]
@idelac3 Do you have a way to reproduce this? Reopen a bug.

**Comment by idelac3** [comment]
Put the following property in your **pom.xml** project file:

```
	<properties>
		<protostuff.version>1.8.0</protostuff.version>
	</properties>
```

and the following dependencies:

```
		<dependency>
			<groupId>io.protostuff</groupId>
			<artifactId>protostuff-core</artifactId>
			<version>${protostuff.version}</version>
		</dependency>
		<dependency>
			<groupId>io.protostuff</groupId>
			<artifactId>protostuff-runtime</artifactId>
			<version>${protostuff.version}</version>
		</dependency>
```

Then, create one simple Enum like the following:

```
public enum MyEnum {

	APPLE, BANANA, ORANGE;
}
```

and the POJO (data that you want to serialize):

```
public class ProtostuffExample {

	private MyEnum myEnum;
	
	private int id;
	private String name;
	
	
	public MyEnum getMyEnum() {
		return myEnum;
	}


	public void setMyEnum(MyEnum myEnum) {
		this.myEnum = myEnum;

	}

        // The rest is ommited, only getters and setters ...
```

The following code will produce warning:

```

	public static void main(String[] args) {

		LinkedBuffer buffer = LinkedBuffer.allocate(LinkedBuffer.DEFAULT_BUFFER_SIZE);

		Schema schema = RuntimeSchema.getSchema(ProtostuffExample.class);

		final ProtostuffExample data = new ProtostuffExample();
		data.setMyEnum(MyEnum.ORANGE);
		data.setId(1);
		data.setName("John");
		
		byte[] payload = ProtostuffIOUtil.toByteArray(data, schema, buffer);
		
		System.out.println(Arrays.toString(payload));
	}
```

Note I'm testing with **JDK 11**.
