### ISSUE TITLE
Do not wrap lists into Collections.unmodifiableList(source) (code generated by java_bean template)

### ISSUE THREAD

**Issue by dyu** [protostuff/protostuff#58]
> Repeated attributes creates an unmodifiable lists after deserialization should be optional

I didn't see this commit.  It should at least be optional, as that will break compatibility with users coming from 1.0.x

The theory is that with anything added, the default behavior is to activate it via a compiler flag/option.

From https://groups.google.com/forum/#!topic/protostuff/ZTee-K6WgMc

**Comment by kshchepanovskyi** [comment]
Fixed
