### ISSUE TITLE
Curious about protostuff joining the csf

### ISSUE THREAD

**Issue by posix4e** [protostuff/protostuff#77]
I have recently started a new software foundation, the CSF. I'd love to discuss in more detail this project being a part of it. The major goals of CSF are:

- Minimal governence to keep projects active and healthy
- Regular ratings on quality 
- Assured public governemence of projects

We are a bit different than the ASF mainly in that:

- We don't believe in such flat structures. Some projects do very will with a dictator
- We don't believe that quality can't be measured. We have some ideas here and are looking for more
- We want to be hands off with process but provide tools to improve project management

What do we think?

**Comment by kshchepanovskyi** [comment]
What exactly CSF gives for project? I can not find this information.

**Comment by posix4e** [comment]
It is still a very early in the development of the foundation. We are working on the charter now. We want to provide assurance to the user, similarly to the asf, while not being as heavy handed.  Also I think as ' neutral position on code quality had been more hindrance than helpful. I think there is some simple things that an organization can do to help assure the project doesn't get info an unmanageable state. 



Sent from Alex Newman
404.507.6749

**Comment by kshchepanovskyi** [comment]
Ok, basically this is not an issue. If there are (now or in the future) some concrete points/steps, let's discuss them separately.
