### ISSUE TITLE
Add @Generated annotation to generated classes

### ISSUE THREAD

**Issue by kshchepanovskyi** [protostuff/protostuff#79]
https://github.com/google/protobuf/issues/42

> javax.annotation.Generated exists since Java 6 (relevant javadoc) so it should be safe to generate source code that contains it. The presence of this annotation has no impact on the runtime characteristics of the annotated classes.
>
> When this annotation is present it greatly helps in configuration of different tools related to code analysis, tests and tests coverage.

http://docs.oracle.com/javase/7/docs/api/javax/annotation/Generated.html

**Comment by dyu** [comment]
If it doesn't have side effects, we can add it in.

**Comment by kshchepanovskyi** [comment]
Yes, it is just a marker for static code analysis tools that is not
accessible in runtime - retention is `SOURCE`.

2015-01-06 10:02 GMT+02:00 David Yu <notifications@github.com>:

> If it doesn't have side effects, we can add it in.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/protostuff/protostuff/issues/79#issuecomment-68836688>
> .
>



-- 
Regards,

Konstantin

**Comment by kshchepanovskyi** [comment]
I faced with interesting issue. 

My idea is to use construction like this: `@Generated("io.protostuff.compiler.ProtoToJavaBeanCompiler")`, `@Generated("io.protostuff.compiler.ProtoToJavaBeanModelCompiler")`.

Looks like it is not so simple. I want to use `@Generated("<codeGeneratorName>")` in templates, but there is no easy  way to pass new argument from compiler class into template (without adding new template argument explicitly).

**Comment by dyu** [comment]
Yea, you'd have to modify ProtoModule to contain extra metadata.
You can use ```<module.output>``` as well.  I think that's clearer as that is what the user directly configures.

**Comment by kshchepanovskyi** [comment]
Thank you, good idea.

2015-01-08 10:18 GMT+02:00 David Yu <notifications@github.com>:

> Yea, you'd have to modify ProtoModule to contain extra metadata.
> You can use <module.output> as well. I think that's clearer as that is
> what the user directly configures.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/protostuff/protostuff/issues/79#issuecomment-69148685>
> .
>



-- 
Regards,

Konstantin
