### ISSUE TITLE
Maven plugin properties

### ISSUE THREAD

**Issue by kshchepanovskyi** [protostuff/protostuff#86]
Add possibility to pass system properties to compiler from maven plugin configuration.
Configuration might look like this:

```xml
<plugin>
        <groupId>io.protostuff</groupId>
        <artifactId>protostuff-maven-plugin</artifactId>
        <version>${protostuff.version}</version>
        <configuration>
          <properties>
            <property>
              <name>ppc.check_filename_placeholder</name>
              <value>true</value>
            </property>
          </properties>
          <protoModules>
...
```

**Comment by dyu** [comment]
Its a bit hacky to override the system props and restore it.
Not sure if that has side effects.

If there aren't any, then its fine with me.

**Comment by kshchepanovskyi** [comment]
It's not a new idea, other maven plugins already use it:

* http://eclipse.org/jetty/documentation/current/jetty-maven-plugin.html#setting-system-properties
* http://maven.apache.org/surefire/maven-surefire-plugin/examples/system-properties.html

Goal is to have all the build configuration in pom, because users want to build project using well-known `mvn clean install` without any additional args.
