### ISSUE TITLE
Improve our mergeFrom performance

### ISSUE THREAD

**Issue by posix4e** [protostuff/protostuff#9]
We are beating the pants off of protobuf except for one metric. The ability to take data out of an inputstream and serialize it. Obviously pipe will give us an advantage but I bet we can beat them outright.

https://github.com/OhmData/protostuffVsProtobuf/issues/5

shows some benchmarks

**Comment by kshchepanovskyi** [comment]
Not enough details, what and how we should improve.  
In general, `mergeFrom` implementation generated by `java_bean` looks optimal, there is no much space for improvements.
