### ISSUE TITLE
equals and hashcode?

### ISSUE THREAD

**Issue by nwertzberger** [protostuff/protostuff#92]
Hello,

Searching the internet says this has already come up, but I'm trying to generate equals and hashcode using the maven plugin to generate from a .proto file. I tried the following plugin configuration to no avail:

    <groupId>io.protostuff</groupId>
    <artifactId>protostuff-maven-plugin</artifactId>
    <version>1.3.1</version>
    <configuration>
        <protoModules>
            <protoModule>
                <source>src/main/proto/ClusterActionStateSchema.proto</source>
                <outputDir>target/generated-sources/proto</outputDir>
                <output>java_bean</output>
                <encoding>UTF-8</encoding>
                <options>
                    <property> <name>generate_helper_methods</name> </property>
                    <property> <name>generate_equals_hashcode</name> </property>
                    <property> <name>generate_field_map</name> </property>
                    <property> <name>builder_pattern</name> </property>
                </options>
            </protoModule>
        </protoModules>
    </configuration>
    <executions>
        <execution>
            <id>generate-sources</id>
            <phase>generate-sources</phase>
            <goals>
                <goal>compile</goal>
            </goals>
        </execution>
    </executions>

Is this supported?

**Comment by kshchepanovskyi** [comment]
Hi,

`java_bean` template does not generate `equals`/`hashCode` implementation.
But you can extend it and add your implementation. For example (using [Java 7 Objects class](http://docs.oracle.com/javase/7/docs/api/java/util/Objects.html)):

```java
message_equals_and_hashcode(message, options) ::= <<
@Override
public boolean equals(Object obj) {
	if (this == obj) {
		return true;
	}
	if (obj == null || this.getClass() != obj.getClass()) {
		return false;
	}
	final <message.name> that = (<message.name>) obj;
	<if(first(message.fields))>
	return
			<message.fields:field_equals(field=it, options=options, message=message); separator=" &&\n">;
	<else>
	return true;
	<endif>
}

@Override
public int hashCode() {
	<if(first(message.fields))>
	return Objects.hash(<message.fields:field_name(field=it, options=options, message=message); separator=", ">);
	<else>
	return 0;
	<endif>
}

>>

field_equals(field, options, message) ::= <<
Objects.equals(this.<var(val=field.name, fmt="CC", options=options)>, that.<var(val=field.name, fmt="CC", options=options)>)
>>
```

Maybe we can add this functionality to the next release - 1.3.2. I need to check how it affects other templates.

**Comment by kshchepanovskyi** [comment]
@dyu please check these issues on google code:

* https://code.google.com/p/protostuff/issues/detail?id=144
* https://code.google.com/p/protostuff/issues/detail?id=166

I think they can be closed.

**Comment by dyu** [comment]
Its not implemented for 1.0.x, leaving it open might be the best option.
I think leaving a comment that it is implemented in 1.3.x is enough.

I've updated the googlecode site stating that no new features will be added for 1.0.x

**Comment by nwertzberger** [comment]
Ladies and gents, you literally can't pay for this type of service. You are all awesome. Is there a donation button for protostuff?

**Comment by dyu** [comment]
Share your experiences.  Spread the word! 
Hope this project benefits yours.
