### ISSUE TITLE
Improve support for messages with sparse/big @Tag values

### ISSUE THREAD

**Issue by kshchepanovskyi** [protostuff/protostuff#98]
Create `RuntimeSchema` for class:

```java
class A {
    @Tag(500_000_000)
    int x;
}
```

Expected result: instance `RuntimeSchema` should be created.
Actual result: `OutOfMemoryError` exception.

**Comment by kshchepanovskyi** [comment]
@dyu What us use-case for `io.protostuff.runtime.RuntimeView`? I could not find any documentation. 

This class is too complex for refactoring - it relies on protected `MappedSchema` fields.
Also, filters `EXCLUDE_OPTIMIZED_FOR_MERGE_ONLY` and `INCLUDE_OPTIMIZED_FOR_MERGE_ONLY` - do they give visible performance improvement? For me it looks like premature optimization.

**Comment by dyu** [comment]
It supports the idea of dynamic filtering (at runtime).
Say on application startup, you read a configuration file (or from a database) and filter your pojos based on the rules.
Normally the use-case is with roles where one would hide certain fields based on the rules of a role.

EXCLUDE_OPTIMIZED_FOR_MERGE_ONLY/INCLUDE_OPTIMIZED_FOR_MERGE_ONLY - if the schema is only used for merging (you never write anything use it), then this is better suited for it as no extra datastructures are created to support writing efficiently.

Say for an incoming rpc request, you want to merge the request with your existing in-memory message/cache.  But you want to be sure that certain fields will never be merged/overwritten.
You will then use either of those two for the purpose of making sure that on merge, those certain fields will be filtered out (excluded).

**Comment by kshchepanovskyi** [comment]
> `EXCLUDE_OPTIMIZED_FOR_MERGE_ONLY`/`INCLUDE_OPTIMIZED_FOR_MERGE_ONLY` - if the schema is only used for merging (you never write anything use it), then this is better suited for it as no extra datastructures are created to support writing efficiently.

As far as I understand, speed is a priority, not memory. In this particular case we save small amount of memory for each view instance (constant number) with the cost of complexity and duplicated code.

I do not want support these two factories (protostuff is not C library for embedded devices with very limited amount of memory). But if you are really sure that we need them - will do proper refactoring for these factories too.

**Comment by dyu** [comment]
Yea its how I code naturally where I try to optimize both speed and memory if its easy to implement.
But, in this case, I don't have a problem if the MERGE_ONLY stuff is removed.
